<?php
$config=array(
	"title"=>"解题",//模块名称
	"module"=>"jieti",//模块目录
 	"version"=>1.0,//当前版本
	"info"=>"解题",//模块信息
	"table_pre"=>"sky_",//表前缀
	"from"=>"www.fd175.com",
	"adminurl"=>"/moduleadmin.php?m=jieti&a=menu",
	"check_update"=>"http://www.deitui.com",
);
?>