<?php
$config=array(
	"title"=>"淘宝客",//模块名称
	"module"=>"taoke",//模块目录
 	"version"=>2.0,//当前版本
	"info"=>"淘宝客",//模块信息
	"table_pre"=>"sky_",//表前缀
	"from"=>"福鼎生活网",
	"adminurl"=>"/moduleadmin.php?m=taoke&a=menu",
	"check_update"=>"http://www.deituicms.com",
);
?>