<?php
$config=array(
	"title"=>"计划任务",//模块名称
	"module"=>"crontask",//模块目录
 	"version"=>3.0,//当前版本
	"info"=>"计划任务",//模块信息
	"table_pre"=>"sky_",//表前缀
	"adminurl"=>"/moduleadmin.php?m=crontask&a=menu",
	"check_update"=>"http://www.deituicms.com",
);
?>