<?php
$config=array(
	"title"=>"助力砍价",//模块名称
	"module"=>"zhuli",//模块目录
 	"version"=>2.0,//当前版本
	"info"=>"助力砍价",//模块信息
	"from"=>"来自福鼎生活网",
	"table_pre"=>"sky_",//表前缀
	"adminurl"=>"/moduleadmin.php?m=zhuli&a=menu",
	"check_update"=>"http://www.deitui.com",
);
?>