<?php
$config=array(
	"title"=>"中秋博饼",//模块名称
	"module"=>"bzy",//模块目录
 	"version"=>1.1,//当前版本
	"info"=>"快速搭建中秋博饼平台",//模块信息
	"table_pre"=>"sky_",//表前缀
	"adminurl"=>"/moduleadmin.php?m=bzy&a=menu",
	"check_update"=>"http://www.deituicms.com",
);
?>