<?php
$config=array(
	"title"=>"阶梯拼团",//模块名称
	"module"=>"fsbuy",//模块目录
 	"version"=>3.0,//当前版本
	"info"=>"阶梯拼团是达到成团人数才生效的团购促销活动",//模块信息
	"table_pre"=>"sky_",//表前缀
	"from"=>"福鼎口福生鲜",
	"adminurl"=>"/moduleadmin.php?m=fsbuy&a=menu",
	"check_update"=>"http://www.deituicms.com",
);
?>