<?php
$config=array(
	"title"=>"共享菜园",//模块名称
	"module"=>"gxny",//模块目录
 	"version"=>1.0,//当前版本
	"info"=>"共享菜园",//模块信息
	"table_pre"=>"sky_",//表前缀
	"adminurl"=>"/moduleadmin.php?m=gxny&a=menu",
	"check_update"=>"http://www.deitui.com",
);
?>