<?php
$config=array(
	"title"=>"imgDiy",//模块名称
	"module"=>"imgdiy",//模块目录
 	"version"=>1.0,//当前版本
	"info"=>"图片设计",//模块信息
	"table_pre"=>"sky_",//表前缀
	"adminurl"=>"/moduleadmin.php?m=imgdiy&a=menu",
	"check_update"=>"http://www.deitui.com",
);
?>