<?php
$config=array(
	"title"=>"vip会员卡",//模块名称
	"module"=>"vipcard",//模块目录
 	"version"=>1.0,//当前版本
	"info"=>"会员卡",//模块信息
	"table_pre"=>"sky_",//表前缀
	"adminurl"=>"/moduleadmin.php?m=vipcard&a=menu",
	"check_update"=>"http://www.deituicms.com",
);
?>