<?php
$config=array(
	"title"=>"分类信息",//模块名称
	"module"=>"fenlei",//模块目录
 	"version"=>4.6,//当前版本
	"info"=>"分类信息",//模块信息
	"from"=>"福鼎生活网",
	"table_pre"=>"sky_",//表前缀
	"adminurl"=>"/moduleadmin.php?m=fenlei&a=menu",
	"check_update"=>"http://www.deituicms.com/index.php?m=checkupdate&product=mod_fenlei",
);
?>