<?php
$config=array(
	"title"=>"企业建站",//模块名称
	"module"=>"qiye",//模块目录
 	"version"=>1.0,//当前版本
	"info"=>"企业建站",//模块信息
	"from"=>"福鼎生活网",
	"table_pre"=>"sky_",//表前缀
	"adminurl"=>"/moduleadmin.php?m=qiye&a=menu",
	"check_update"=>"http://www.deitui.com",
);
?>