<?php
$config=array(
	"title"=>"直播购物导航",//模块名称
	"module"=>"zbtao",//模块目录
 	"version"=>1,//当前版本
	"info"=>"直播购物导航",//模块信息
	"table_pre"=>"sky_",//表前缀
	"adminurl"=>"/moduleadmin.php?m=zbtao&a=menu",
	"check_update"=>"http://www.deituicms.com",
);
?>