<?php
$config=array(
	"title"=>"族谱",//模块名称
	"module"=>"zupu",//模块目录
 	"version"=>2.0,//当前版本
	"info"=>"族谱",//模块信息
	"from"=>"来自福鼎生活网",
	"table_pre"=>"sky_",//表前缀
	"adminurl"=>"/moduleadmin.php?m=zupu&a=menu",
	"check_update"=>"http://www.deitui.com",
);
?>