<?php
$config=array(
	"title"=>"返利商城",//模块名称
	"module"=>"flk",//模块目录
 	"version"=>1.0,//当前版本
	"info"=>"flk商城",//模块信息
	"table_pre"=>"sky_",//表前缀
	"adminurl"=>"/moduleadmin.php?m=flk&a=menu",
	"check_update"=>"http://www.deituicms.com",
);
?>