<?php
$content=<<<eof
drop table sky_mod_flk_account ;
drop table sky_mod_flk_account_log ;
drop table sky_mod_flk_admin ;
drop table sky_mod_flk_article ;
drop table sky_mod_flk_article_comment ;
drop table sky_mod_flk_article_data ;
drop table sky_mod_flk_bankcard ;
drop table sky_mod_flk_cart ;
drop table sky_mod_flk_category ;
drop table sky_mod_flk_cbd ;
drop table sky_mod_flk_cbd_shop ;
drop table sky_mod_flk_coupon ;
drop table sky_mod_flk_coupon_user ;
drop table sky_mod_flk_daxin ;
drop table sky_mod_flk_daxin_log ;
drop table sky_mod_flk_express_fee ;
drop table sky_mod_flk_express_fee_city ;
drop table sky_mod_flk_group ;
drop table sky_mod_flk_group_product ;
drop table sky_mod_flk_guest ;
drop table sky_mod_flk_guestindex ;
drop table sky_mod_flk_order ;
drop table sky_mod_flk_order_address ;
drop table sky_mod_flk_order_code ;
drop table sky_mod_flk_order_data ;
drop table sky_mod_flk_order_log ;
drop table sky_mod_flk_order_product ;
drop table sky_mod_flk_order_raty ;
drop table sky_mod_flk_product ;
drop table sky_mod_flk_product_data ;
drop table sky_mod_flk_product_ks ;
drop table sky_mod_flk_queue ;
drop table sky_mod_flk_queue_log ;
drop table sky_mod_flk_report ;
drop table sky_mod_flk_shop ;
drop table sky_mod_flk_shop_apply ;
drop table sky_mod_flk_shop_category ;
drop table sky_mod_flk_shop_commission ;
drop table sky_mod_flk_shop_earnest ;
drop table sky_mod_flk_shop_earnest_log ;
drop table sky_mod_flk_shop_earnest_refund ;
drop table sky_mod_flk_shop_money ;
drop table sky_mod_flk_shop_money_log ;
drop table sky_mod_flk_shop_notice ;
drop table sky_mod_flk_shop_openbind ;
drop table sky_mod_flk_shop_paypwd ;
drop table sky_mod_flk_shop_product_category ;
drop table sky_mod_flk_shop_safephone ;
drop table sky_mod_flk_video ;
drop table sky_mod_flk_view_user ;

eof;
?>