<?php
$config=array(
	"title"=>"考卷测试",//模块名称
	"module"=>"exam",//模块目录
 	"version"=>1.2,//当前版本
	"info"=>"考卷测试",//模块信息
	"table_pre"=>"sky_",//表前缀
	"adminurl"=>"/moduleadmin.php?m=exam&a=menu",
	"check_update"=>"http://www.deitui.com",
);
?>