<?php
$config=array(
	"title"=>"得推多用户拼团商城",//模块名称
	"module"=>"pdd",//模块目录
 	"version"=>1.0,//当前版本
	"info"=>"得推多用户拼团商城",//模块信息
	"table_pre"=>"sky_",//表前缀
	"adminurl"=>"/moduleadmin.php?m=pdd&a=menu",
	"check_update"=>"http://www.deituicms.com",
);
?>