<?php
$config=array(
	"title"=>"im",//模块名称
	"module"=>"im",//模块目录
 	"version"=>1.0,//当前版本
	"info"=>"im应用",//模块信息
	"table_pre"=>"sky_",//表前缀
	"adminurl"=>"/moduleadmin.php?m=im&a=menu",
	"check_update"=>"http://www.deitui.com",
);
?>