<?php
$config=array(
	"title"=>"分享图片",//模块名称
	"module"=>"sharepic",//模块目录
 	"version"=>1.0,//当前版本
	"info"=>"分享图片",//模块信息
	"from"=>"来自福鼎生活网",
	"table_pre"=>"sky_",//表前缀
	"adminurl"=>"/moduleadmin.php?m=sharepic&a=menu",
	"check_update"=>"http://www.deitui.com",
);
?>