<?php
$config=array(
	"title"=>"微博客",//模块名称
	"module"=>"sblog",//模块目录
 	"version"=>2.0,//当前版本
	"info"=>"微博客快速发帖交流",//模块信息
	"from"=>"福鼎生活网",
	"table_pre"=>"sky_",//表前缀
	"adminurl"=>"/moduleadmin.php?m=sblog&a=menu",
	"check_update"=>"http://www.deituicms.com",
);
?>