<?php
$config=array(
	"title"=>"分销商城",//模块名称
	"module"=>"f2c",//模块目录
 	"version"=>1.0,//当前版本
	"info"=>"分销商城",//模块信息
	"table_pre"=>"sky_",//表前缀
	"adminurl"=>"/moduleadmin.php?m=f2c&a=menu",
	"check_update"=>"http://www.deitui.com",
);
?>