<?php
$config=array(
	"title"=>"elsearch",//模块名称
	"module"=>"elsearch",//模块目录
 	"version"=>1.1,//当前版本
	"info"=>"全文搜索",//模块信息
	"table_pre"=>"sky_",//表前缀
	"adminurl"=>"/moduleadmin.php?m=elsearch&a=menu",
	"check_update"=>"http://www.deituicms.com",
);
?>