<?php
$config=array(
	"title"=>"主打菜",//模块名称
	"module"=>"mdish",//模块目录
 	"version"=>1.0,//当前版本
	"info"=>"主打菜",//模块信息
	"table_pre"=>"sky_",//表前缀
	"from"=>"福鼎口福生鲜",
	"adminurl"=>"moduleadmin.php?m=mdish&a=menu",
	"check_update"=>"http://www.deituicms.com",
);
?>