<?php
$config=array(
	"title"=>"diyPage",//模块名称
	"module"=>"diypage",//模块目录
 	"version"=>1.0,//当前版本
	"info"=>"页面diy",//模块信息
	"table_pre"=>"sky_",//表前缀
	"adminurl"=>"/moduleadmin.php?m=diypage&a=menu",
	"check_update"=>"http://www.deitui.com",
);
?>