<?php
$config=array(
	"title"=>"盲盒交友",//模块名称
	"module"=>"yxq",//模块目录
 	"version"=>1.0,//当前版本
	"info"=>"盲盒交友",//模块信息
	"table_pre"=>"sky_",//表前缀
	"adminurl"=>"/moduleadmin.php?m=yxq&a=menu",
	"check_update"=>"http://www.deituicms.com",
);
?>