<?php
$config=array(
	"title"=>"拼车",//模块名称
	"module"=>"pinche",//模块目录
 	"version"=>2.3,//当前版本
	"info"=>"拼车",//模块信息
	"from"=>"福鼎生活网",
	"table_pre"=>"sky_",//表前缀
	"adminurl"=>"/moduleadmin.php?m=pinche&a=menu",
	"check_update"=>"http://www.deitui.com",
);
?>