<?php
$config=array(
	"title"=>"团队协作",//模块名称
	"module"=>"teamwork",//模块目录
 	"version"=>1.0,//当前版本
	"info"=>"团队协作",//模块信息
	"table_pre"=>"sky_",//表前缀
	"adminurl"=>"/moduleadmin.php?m=teamwork&a=menu",
	"check_update"=>"http://www.deituicms.com",
);
?>