<?php
$config=array(
	"title"=>"xseo",//模块名称
	"module"=>"xseo",//模块目录
 	"version"=>1.0,//当前版本
	"info"=>"xseo",//模块信息
	"table_pre"=>"sky_",//表前缀
	"from"=>"福鼎生活网",
	"adminurl"=>"/moduleadmin.php?m=xseo&a=menu",
	"check_update"=>"http://www.deituicms.com",
);
?>