<?php
$config=array(
	"title"=>"同城家教",//模块名称
	"module"=>"tutor",//模块目录
 	"version"=>1.0,//当前版本
	"info"=>"同城家教",//模块信息
	"table_pre"=>"sky_",//表前缀
	"adminurl"=>"/moduleadmin.php?m=tutor&a=menu",
	"check_update"=>"http://www.deituicms.com",
);
?>