<?php
$config=array(
	"title"=>"快回收",
	"module"=>"recycle",
	"version"=>1.1,//当前版本
	"info"=>"快回收",//模块信息
	"first"=>"首发于福鼎生活网",
	"table_pre"=>"sky_",//表前缀
	"adminurl"=>"/moduleadmin.php?m=recycle&a=menu",
	"check_update"=>"http://www.skymvc.com",
);