<?php
$config=array(
	"title"=>"多城市家政派单",//模块名称
	"module"=>"mmjz",//模块目录
 	"version"=>3.0,//当前版本
	"info"=>"多城市家政派单商城",//模块信息
	"table_pre"=>"sky_",//表前缀
	"from"=>"福鼎生活网",
	"adminurl"=>"/moduleadmin.php?m=mmjz&a=menu",
	"check_update"=>"http://www.deituicms.com",
);
?>