<?php
$content=<<<eof
drop table sky_mod_mmjz_admin ;
drop table sky_mod_mmjz_article ;
drop table sky_mod_mmjz_article_comment ;
drop table sky_mod_mmjz_article_data ;
drop table sky_mod_mmjz_auth_user ;
drop table sky_mod_mmjz_bankcard ;
drop table sky_mod_mmjz_blog ;
drop table sky_mod_mmjz_blog_comment ;
drop table sky_mod_mmjz_blog_view ;
drop table sky_mod_mmjz_brand ;
drop table sky_mod_mmjz_cart ;
drop table sky_mod_mmjz_category ;
drop table sky_mod_mmjz_cbd ;
drop table sky_mod_mmjz_cbd_shop ;
drop table sky_mod_mmjz_coupon ;
drop table sky_mod_mmjz_coupon_user ;
drop table sky_mod_mmjz_express_fee ;
drop table sky_mod_mmjz_express_fee_city ;
drop table sky_mod_mmjz_group ;
drop table sky_mod_mmjz_group_product ;
drop table sky_mod_mmjz_guest ;
drop table sky_mod_mmjz_guestindex ;
drop table sky_mod_mmjz_hotvip ;
drop table sky_mod_mmjz_order ;
drop table sky_mod_mmjz_order_address ;
drop table sky_mod_mmjz_order_code ;
drop table sky_mod_mmjz_order_data ;
drop table sky_mod_mmjz_order_log ;
drop table sky_mod_mmjz_order_product ;
drop table sky_mod_mmjz_order_raty ;
drop table sky_mod_mmjz_product ;
drop table sky_mod_mmjz_product_data ;
drop table sky_mod_mmjz_product_ks ;
drop table sky_mod_mmjz_report ;
drop table sky_mod_mmjz_shop ;
drop table sky_mod_mmjz_shop_apply ;
drop table sky_mod_mmjz_shop_category ;
drop table sky_mod_mmjz_shop_cert ;
drop table sky_mod_mmjz_shop_commission ;
drop table sky_mod_mmjz_shop_earnest ;
drop table sky_mod_mmjz_shop_earnest_log ;
drop table sky_mod_mmjz_shop_earnest_refund ;
drop table sky_mod_mmjz_shop_hotvip ;
drop table sky_mod_mmjz_shop_hotvip_user ;
drop table sky_mod_mmjz_shop_money ;
drop table sky_mod_mmjz_shop_money_log ;
drop table sky_mod_mmjz_shop_notice ;
drop table sky_mod_mmjz_shop_openbind ;
drop table sky_mod_mmjz_shop_paypwd ;
drop table sky_mod_mmjz_shop_product_category ;
drop table sky_mod_mmjz_shop_safephone ;
drop table sky_mod_mmjz_video ;
drop table sky_mod_mmjz_view_user ;

eof;
?>