<?php
$config=array(
	"title"=>"钓鱼",//模块名称
	"module"=>"fishing",//模块目录
 	"version"=>1.0,//当前版本
	"info"=>"钓鱼",//模块信息
	"from"=>"福鼎生活网",
	"table_pre"=>"sky_",//表前缀
	"adminurl"=>"/moduleadmin.php?m=fishing&a=menu",
	"check_update"=>"http://www.deituicms.com/index.php?m=checkupdate&product=mod_fishing",
);
?>