<?php
$content=<<<eof
drop table sky_mod_b2b_admin ;
drop table sky_mod_b2b_article ;
drop table sky_mod_b2b_article_comment ;
drop table sky_mod_b2b_article_data ;
drop table sky_mod_b2b_auth_user ;
drop table sky_mod_b2b_bankcard ;
drop table sky_mod_b2b_blog ;
drop table sky_mod_b2b_blog_comment ;
drop table sky_mod_b2b_blog_view ;
drop table sky_mod_b2b_brand ;
drop table sky_mod_b2b_cart ;
drop table sky_mod_b2b_category ;
drop table sky_mod_b2b_cbd ;
drop table sky_mod_b2b_cbd_shop ;
drop table sky_mod_b2b_coupon ;
drop table sky_mod_b2b_coupon_user ;
drop table sky_mod_b2b_express_fee ;
drop table sky_mod_b2b_express_fee_city ;
drop table sky_mod_b2b_group ;
drop table sky_mod_b2b_group_product ;
drop table sky_mod_b2b_guest ;
drop table sky_mod_b2b_guestindex ;
drop table sky_mod_b2b_hotvip ;
drop table sky_mod_b2b_order ;
drop table sky_mod_b2b_order_address ;
drop table sky_mod_b2b_order_code ;
drop table sky_mod_b2b_order_data ;
drop table sky_mod_b2b_order_log ;
drop table sky_mod_b2b_order_product ;
drop table sky_mod_b2b_order_raty ;
drop table sky_mod_b2b_product ;
drop table sky_mod_b2b_product_data ;
drop table sky_mod_b2b_product_ks ;
drop table sky_mod_b2b_report ;
drop table sky_mod_b2b_shop ;
drop table sky_mod_b2b_shop_apply ;
drop table sky_mod_b2b_shop_category ;
drop table sky_mod_b2b_shop_cert ;
drop table sky_mod_b2b_shop_commission ;
drop table sky_mod_b2b_shop_earnest ;
drop table sky_mod_b2b_shop_earnest_log ;
drop table sky_mod_b2b_shop_earnest_refund ;
drop table sky_mod_b2b_shop_hotvip ;
drop table sky_mod_b2b_shop_hotvip_user ;
drop table sky_mod_b2b_shop_money ;
drop table sky_mod_b2b_shop_money_log ;
drop table sky_mod_b2b_shop_notice ;
drop table sky_mod_b2b_shop_openbind ;
drop table sky_mod_b2b_shop_paypwd ;
drop table sky_mod_b2b_shop_product_category ;
drop table sky_mod_b2b_shop_safephone ;
drop table sky_mod_b2b_video ;
drop table sky_mod_b2b_view_user ;

eof;
?>