<?php
$config=array(
	"title"=>"采集插件",//模块名称
	"module"=>"collect",//模块目录
 	"version"=>1.0,//当前版本
	"info"=>"采集插件可以采集网上内容",//模块信息
	"table_pre"=>"sky_",//表前缀
	"adminurl"=>"/moduleadmin.php?m=collect&a=menu",
	"check_update"=>"http://www.deituicms.com",
);
?>