<?php
$config=array(
	"title"=>"扫码点餐",//模块名称
	"module"=>"cy2c",//模块目录
 	"version"=>1.0,//当前版本
	"info"=>"一款可以用来到店消费按座位下单的餐饮店程序，可以按座下单，也可以直接下单",//模块信息
	"table_pre"=>"sky_",//表前缀
	"adminurl"=>"/moduleadmin.php?m=cy2c&a=menu",
	"check_update"=>"http://www.deitui.com",
);
?>