<?php
$config=array(
	"title"=>"微圈子",//模块名称
	"module"=>"group",//模块目录
 	"version"=>1.0,//当前版本
	"info"=>"微圈子可以让各种群体加入",//模块信息
	"from"=>"来自福鼎生活网",
	"table_pre"=>"sky_",//表前缀
	"adminurl"=>"/moduleadmin.php?m=group&a=menu",
	"check_update"=>"http://www.skymvc.com",
);
?>