<?php
$config=array(
	"title"=>"金币市场",//模块名称
	"module"=>"gold",//模块目录
 	"version"=>1.0,//当前版本
	"info"=>"金币市场可以用金币兑换其它商品",//模块信息
	"table_pre"=>"sky_",//表前缀
	"adminurl"=>"/moduleadmin.php?m=gold&a=menu",
	"check_update"=>"http://www.deitui.com",
);
?>