<?php
$config=array(
	"title"=>"活动报名party",//模块名称
	"module"=>"party",//模块目录
 	"version"=>1.0,//当前版本
	"info"=>"活动报名",//模块信息
	"table_pre"=>"sky_",//表前缀
	"adminurl"=>"/moduleadmin.php?m=party&a=menu",
	"check_update"=>"http://www.deitui.com",
);
?>