<?php
$config=array(
	"title"=>"景点在线",//模块名称
	"module"=>"jdo2o",//模块目录
 	"version"=>1.0,//当前版本
	"info"=>"景点在线",//模块信息
	"table_pre"=>"sky_",//表前缀
	"from"=>"福鼎生活网",
	"adminurl"=>"/moduleadmin.php?m=jdo2o&a=menu",
	"check_update"=>"http://www.deituicms.com",
);
?>