<?php
$content=<<<eof
drop table sky_mod_jdo2o_admin ;
drop table sky_mod_jdo2o_article ;
drop table sky_mod_jdo2o_article_comment ;
drop table sky_mod_jdo2o_bankcard ;
drop table sky_mod_jdo2o_blog ;
drop table sky_mod_jdo2o_blog_comment ;
drop table sky_mod_jdo2o_blog_view ;
drop table sky_mod_jdo2o_cart ;
drop table sky_mod_jdo2o_category ;
drop table sky_mod_jdo2o_cbd ;
drop table sky_mod_jdo2o_cbd_shop ;
drop table sky_mod_jdo2o_coupon ;
drop table sky_mod_jdo2o_coupon_user ;
drop table sky_mod_jdo2o_express_fee ;
drop table sky_mod_jdo2o_express_fee_city ;
drop table sky_mod_jdo2o_follow ;
drop table sky_mod_jdo2o_group ;
drop table sky_mod_jdo2o_group_product ;
drop table sky_mod_jdo2o_guest ;
drop table sky_mod_jdo2o_guestindex ;
drop table sky_mod_jdo2o_order ;
drop table sky_mod_jdo2o_order_address ;
drop table sky_mod_jdo2o_order_code ;
drop table sky_mod_jdo2o_order_data ;
drop table sky_mod_jdo2o_order_log ;
drop table sky_mod_jdo2o_order_product ;
drop table sky_mod_jdo2o_order_raty ;
drop table sky_mod_jdo2o_place ;
drop table sky_mod_jdo2o_place_comment ;
drop table sky_mod_jdo2o_place_vr3d ;
drop table sky_mod_jdo2o_product ;
drop table sky_mod_jdo2o_product_data ;
drop table sky_mod_jdo2o_product_ks ;
drop table sky_mod_jdo2o_report ;
drop table sky_mod_jdo2o_shop ;
drop table sky_mod_jdo2o_shop_apply ;
drop table sky_mod_jdo2o_shop_category ;
drop table sky_mod_jdo2o_shop_commission ;
drop table sky_mod_jdo2o_shop_earnest ;
drop table sky_mod_jdo2o_shop_earnest_log ;
drop table sky_mod_jdo2o_shop_earnest_refund ;
drop table sky_mod_jdo2o_shop_money ;
drop table sky_mod_jdo2o_shop_money_log ;
drop table sky_mod_jdo2o_shop_notice ;
drop table sky_mod_jdo2o_shop_openbind ;
drop table sky_mod_jdo2o_shop_paypwd ;
drop table sky_mod_jdo2o_shop_product_category ;
drop table sky_mod_jdo2o_shop_safephone ;
drop table sky_mod_jdo2o_video ;
drop table sky_mod_jdo2o_view_user ;

eof;
?>