<?php
$config=array(
	"title"=>"邻里拼团",//模块名称
	"module"=>"lltuan",//模块目录
 	"version"=>1.0,//当前版本
	"info"=>"邻里拼团",//模块信息
	"from"=>"来自福鼎生活网",
	"table_pre"=>"sky_",//表前缀
	"adminurl"=>"/moduleadmin.php?m=lltuan&a=menu",
	"check_update"=>"http://www.deituicms.com",
);
?>