<?php
$config=array(
	"title"=>"幸运大转盘",//模块名称
	"module"=>"dzp",//模块目录
 	"version"=>1.1,//当前版本
	"info"=>"幸运大转盘是一款幸运大转盘促销",//模块信息
	"table_pre"=>"sky_",//表前缀
	"adminurl"=>"/moduleadmin.php?m=dzp&a=menu",
	"check_update"=>"http://www.deituicms.com",
);
?>