<?php
$config=array(
	"title"=>"财务账单",//模块名称
	"module"=>"bill",//模块目录
 	"version"=>1.00,//当前版本
	"info"=>"简单的收支账本",//模块信息
	"table_pre"=>"sky_",//表前缀
	"from"=>"福鼎生活网",
	"adminurl"=>"/moduleadmin.php?m=bill&a=menu",
	"check_update"=>"http://www.deituicms.com",
);
?>